checkpoint:
  monitor: val/acc
  mode: max
  save_top_k: 3
  filename: "best-{epoch:02d}"
early_stopping:
  monitor: val/acc
  mode: max
  patience: 20
learning_rate_monitor:
  enabled: true
  callback:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: epoch
    log_momentum: false
