defaults:
  - data: lasr
  - encoder: sparsh_ijepa_base
  - temporal_encoder: default
  - head: mlp
  - lightning: default
  - trainer: default
  - callbacks: default
  - logger: mlflow
  - _self_
